"""add_hospital_accreditation_profile

Revision ID: 02c7a488c69e
Revises: 7ec208e12d9f
Create Date: 2026-06-08 03:46:16.082725
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '02c7a488c69e'
down_revision: Union[str, None] = '7ec208e12d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_accreditation_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('bed_count', sa.Integer(), nullable=False),
    sa.Column('hospital_type', sa.String(length=50), nullable=True),
    sa.Column('profile_status', sa.Enum('DRAFT', 'COMPLETE', 'NEEDS_REVIEW', name='profilestatus'), nullable=False),
    sa.Column('services_offered', sa.JSON(), nullable=False),
    sa.Column('specialty_services', sa.JSON(), nullable=False),
    sa.Column('has_icu', sa.Boolean(), nullable=False),
    sa.Column('has_operation_theatre', sa.Boolean(), nullable=False),
    sa.Column('has_emergency', sa.Boolean(), nullable=False),
    sa.Column('has_pharmacy', sa.Boolean(), nullable=False),
    sa.Column('has_lab', sa.Boolean(), nullable=False),
    sa.Column('has_blood_bank', sa.Boolean(), nullable=False),
    sa.Column('has_ambulance', sa.Boolean(), nullable=False),
    sa.Column('has_maternity', sa.Boolean(), nullable=False),
    sa.Column('has_dialysis', sa.Boolean(), nullable=False),
    sa.Column('has_imaging', sa.Boolean(), nullable=False),
    sa.Column('has_cssd', sa.Boolean(), nullable=False),
    sa.Column('annual_patient_volume', sa.Integer(), nullable=True),
    sa.Column('avg_monthly_opd', sa.Integer(), nullable=True),
    sa.Column('scope_exclusions', sa.JSON(), nullable=False),
    sa.Column('last_scoped_at', sa.DateTime(), nullable=True),
    sa.Column('scoped_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id')
    )
    op.create_index('idx_accred_profile_hospital', 'hospital_accreditation_profiles', ['hospital_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_accred_profile_hospital', table_name='hospital_accreditation_profiles')
    op.drop_table('hospital_accreditation_profiles')
    # ### end Alembic commands ###
