"""initial_baseline

Revision ID: 7ec208e12d9f
Revises: 
Create Date: 2026-06-08 03:37:16.931685
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '7ec208e12d9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('fcra_number', sa.String(length=100), nullable=True),
    sa.Column('fcra_expiry', sa.DateTime(), nullable=True),
    sa.Column('nabh_accreditation_id', sa.String(length=100), nullable=True),
    sa.Column('nabh_edition', sa.String(length=20), nullable=True),
    sa.Column('nabh_expiry', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('hospital_type', sa.String(length=50), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('is_rural', sa.Boolean(), nullable=True),
    sa.Column('has_emergency', sa.Boolean(), nullable=True),
    sa.Column('has_icu', sa.Boolean(), nullable=True),
    sa.Column('has_operation_theatre', sa.Boolean(), nullable=True),
    sa.Column('overall_risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'MINIMAL', name='risklevel'), nullable=True),
    sa.Column('last_audit_date', sa.DateTime(), nullable=True),
    sa.Column('next_audit_date', sa.DateTime(), nullable=True),
    sa.Column('onboarding_stage', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcra_number'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('nabh_editions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'RETIRED', name='editionstatus'), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('regulatory_updates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('update_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('semantic_diff', sa.Text(), nullable=True),
    sa.Column('impact_analysis', sa.Text(), nullable=True),
    sa.Column('affected_areas', sa.JSON(), nullable=True),
    sa.Column('compliance_actions_required', sa.JSON(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('embeddings_stored', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regulatory_date', 'regulatory_updates', ['published_date'], unique=False)
    op.create_index('idx_regulatory_source', 'regulatory_updates', ['source'], unique=False)
    op.create_table('data_breach_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=True),
    sa.Column('breach_detected_at', sa.DateTime(), nullable=False),
    sa.Column('breach_type', sa.String(length=100), nullable=True),
    sa.Column('affected_records_count', sa.Integer(), nullable=True),
    sa.Column('data_categories_affected', sa.JSON(), nullable=True),
    sa.Column('contained_at', sa.DateTime(), nullable=True),
    sa.Column('notified_dpo_at', sa.DateTime(), nullable=True),
    sa.Column('notified_board_at', sa.DateTime(), nullable=True),
    sa.Column('notified_patients_at', sa.DateTime(), nullable=True),
    sa.Column('notified_dpdp_board_at', sa.DateTime(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_actions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('fund_type', sa.Enum('FCRA_FOREIGN', 'FCRA_DOMESTIC', 'GOVERNMENT_GRANT', 'PATIENT_FEES', 'DONATION_DOMESTIC', 'CSR_FUNDS', name='fundtype'), nullable=False),
    sa.Column('is_fcra_designated', sa.Boolean(), nullable=True),
    sa.Column('fcra_utilization_purpose', sa.Text(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('annual_budget', sa.Float(), nullable=True),
    sa.Column('ytd_expenditure', sa.Float(), nullable=True),
    sa.Column('last_reconciliation', sa.DateTime(), nullable=True),
    sa.Column('compliance_status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'PARTIALLY_COMPLIANT', 'UNDER_REVIEW', 'NOT_APPLICABLE', name='compliancestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licenses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('license_name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('license_type', sa.String(length=100), nullable=True),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('renewal_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRING_SOON', 'EXPIRED', 'RENEWAL_IN_PROGRESS', 'SUSPENDED', name='licensestatus'), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=True),
    sa.Column('renewal_reminder_days', sa.Integer(), nullable=True),
    sa.Column('last_reminder_sent', sa.DateTime(), nullable=True),
    sa.Column('renewal_application_filed', sa.Boolean(), nullable=True),
    sa.Column('renewal_application_date', sa.DateTime(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_license_expiry', 'licenses', ['expiry_date'], unique=False)
    op.create_index('idx_license_status', 'licenses', ['status'], unique=False)
    op.create_table('nabh_chapters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('canonical_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['nabh_editions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'canonical_code', name='uq_chapter_edition_code')
    )
    op.create_index('idx_chapter_edition', 'nabh_chapters', ['edition_id'], unique=False)
    op.create_table('nabh_source_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('edition_version', sa.String(length=50), nullable=False),
    sa.Column('file_path_or_url', sa.String(length=500), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['nabh_editions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_doc_edition', 'nabh_source_documents', ['edition_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'HOSPITAL_ADMIN', 'COMPLIANCE_OFFICER', 'DOCTOR', 'NURSE', 'PHARMACIST', 'LAB_TECHNICIAN', 'ACCOUNTANT', 'WARD_BOY', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('registration_expiry', sa.DateTime(), nullable=True),
    sa.Column('training_records', sa.JSON(), nullable=True),
    sa.Column('last_training_date', sa.DateTime(), nullable=True),
    sa.Column('next_training_due', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('bmw_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('waste_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.Enum('YELLOW', 'RED', 'WHITE', 'BLUE', 'BLACK', name='bmwcategory'), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('source_department', sa.String(length=100), nullable=True),
    sa.Column('source_ward', sa.String(length=100), nullable=True),
    sa.Column('treatment_method', sa.String(length=50), nullable=True),
    sa.Column('treatment_date', sa.DateTime(), nullable=True),
    sa.Column('treatment_operator', sa.String(length=255), nullable=True),
    sa.Column('treatment_machine_id', sa.String(length=100), nullable=True),
    sa.Column('treatment_temperature', sa.Float(), nullable=True),
    sa.Column('treatment_duration_min', sa.Integer(), nullable=True),
    sa.Column('disposal_date', sa.DateTime(), nullable=True),
    sa.Column('disposal_agency', sa.String(length=255), nullable=True),
    sa.Column('disposal_manifest_number', sa.String(length=100), nullable=True),
    sa.Column('disposal_vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('is_properly_segregated', sa.Boolean(), nullable=True),
    sa.Column('is_properly_labeled', sa.Boolean(), nullable=True),
    sa.Column('is_properly_stored', sa.Boolean(), nullable=True),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('ai_classification', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('recorded_by', sa.String(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bmw_category', 'bmw_logs', ['category'], unique=False)
    op.create_index('idx_bmw_date', 'bmw_logs', ['waste_date'], unique=False)
    op.create_index('idx_bmw_hospital_date', 'bmw_logs', ['hospital_id', 'waste_date'], unique=False)
    op.create_table('compliance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('standard_code', sa.String(length=50), nullable=False),
    sa.Column('standard_name', sa.String(length=255), nullable=True),
    sa.Column('chapter', sa.String(length=100), nullable=True),
    sa.Column('element_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'PARTIALLY_COMPLIANT', 'UNDER_REVIEW', 'NOT_APPLICABLE', name='compliancestatus'), nullable=True),
    sa.Column('evidence_path', sa.String(length=500), nullable=True),
    sa.Column('evidence_description', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('gap_percentage', sa.Float(), nullable=True),
    sa.Column('remediation_plan', sa.Text(), nullable=True),
    sa.Column('remediation_deadline', sa.DateTime(), nullable=True),
    sa.Column('remediation_owner', sa.String(), nullable=True),
    sa.Column('last_assessed', sa.DateTime(), nullable=True),
    sa.Column('assessed_by', sa.String(length=255), nullable=True),
    sa.Column('next_assessment', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['remediation_owner'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compliance_standard', 'compliance_records', ['standard_code'], unique=False)
    op.create_index('idx_compliance_status', 'compliance_records', ['status'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('patient_name_hash', sa.String(length=64), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('patient_mobile', sa.String(length=20), nullable=True),
    sa.Column('patient_address', sa.Text(), nullable=True),
    sa.Column('digital_signature', sa.Text(), nullable=True),
    sa.Column('consent_type', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('data_categories', sa.JSON(), nullable=True),
    sa.Column('third_parties', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('GRANTED', 'DENIED', 'WITHDRAWN', 'EXPIRED', 'PENDING', name='consentstatus'), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('consent_method', sa.String(length=50), nullable=True),
    sa.Column('witness_id', sa.String(), nullable=True),
    sa.Column('otp_verified', sa.Boolean(), nullable=True),
    sa.Column('artefact_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp_proof', sa.Text(), nullable=True),
    sa.Column('is_minor', sa.Boolean(), nullable=True),
    sa.Column('guardian_consent_id', sa.String(), nullable=True),
    sa.Column('language_preference', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['witness_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consent_expiry', 'consent_records', ['expires_at'], unique=False)
    op.create_index('idx_consent_patient', 'consent_records', ['patient_id'], unique=False)
    op.create_index('idx_consent_status', 'consent_records', ['status'], unique=False)
    op.create_table('fund_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('donor_name', sa.String(length=255), nullable=True),
    sa.Column('donor_country', sa.String(length=100), nullable=True),
    sa.Column('donor_passport_or_id', sa.String(length=100), nullable=True),
    sa.Column('utilization_certificate_ref', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('is_compliant', sa.Boolean(), nullable=True),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['fund_accounts.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fund_type_date', 'fund_transactions', ['account_id', 'transaction_date'], unique=False)
    op.create_index('idx_transaction_date', 'fund_transactions', ['transaction_date'], unique=False)
    op.create_table('nabh_objectives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('chapter_code', sa.String(length=50), nullable=False),
    sa.Column('objective_number', sa.Integer(), nullable=False),
    sa.Column('element_letter', sa.String(length=10), nullable=False),
    sa.Column('standard_code', sa.String(length=100), nullable=False),
    sa.Column('standard_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', name='severitylevel'), nullable=True),
    sa.Column('maturity_level', sa.Enum('NON_EXISTENT', 'AD_HOC', 'DEFINED', 'IMPLEMENTED', 'MEASURED', 'OPTIMIZED', name='maturitylevel'), nullable=True),
    sa.Column('policy_doc_url', sa.String(length=500), nullable=True),
    sa.Column('implementation_logs_count', sa.Integer(), nullable=True),
    sa.Column('monitoring_indicator_rate', sa.Float(), nullable=True),
    sa.Column('cqi_project_id', sa.String(length=100), nullable=True),
    sa.Column('remediation_plan', sa.Text(), nullable=True),
    sa.Column('remediation_deadline', sa.DateTime(), nullable=True),
    sa.Column('remediation_owner', sa.String(), nullable=True),
    sa.Column('last_assessed', sa.DateTime(), nullable=True),
    sa.Column('assessed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['remediation_owner'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nabh_standards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('canonical_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['nabh_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edition_id'], ['nabh_editions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'canonical_code', name='uq_standard_edition_code')
    )
    op.create_index('idx_standard_chapter', 'nabh_standards', ['chapter_id'], unique=False)
    op.create_index('idx_standard_edition', 'nabh_standards', ['edition_id'], unique=False)
    op.create_table('risk_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'MINIMAL', name='risklevel'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_resolved', 'risk_alerts', ['is_resolved'], unique=False)
    op.create_index('idx_alert_severity', 'risk_alerts', ['severity'], unique=False)
    op.create_index('idx_alert_type', 'risk_alerts', ['alert_type'], unique=False)
    op.create_table('nabh_objective_elements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('standard_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('canonical_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', name='severitylevel'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['nabh_editions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_id'], ['nabh_standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'canonical_code', name='uq_obj_element_edition_code')
    )
    op.create_index('idx_obj_element_edition', 'nabh_objective_elements', ['edition_id'], unique=False)
    op.create_index('idx_obj_element_standard', 'nabh_objective_elements', ['standard_id'], unique=False)
    op.create_table('nabh_measurable_elements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('objective_element_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('canonical_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('applicability_default', sa.Enum('APPLICABLE', 'CONDITIONAL', 'NOT_APPLICABLE', 'MANUAL_REVIEW', name='applicabilitydefault'), nullable=False),
    sa.Column('scoring_weight', sa.Float(), nullable=False),
    sa.Column('risk_weight', sa.Float(), nullable=False),
    sa.Column('default_owner_role', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['nabh_editions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_element_id'], ['nabh_objective_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'canonical_code', name='uq_meas_element_edition_code')
    )
    op.create_index('idx_meas_element_edition', 'nabh_measurable_elements', ['edition_id'], unique=False)
    op.create_index('idx_meas_element_obj_el', 'nabh_measurable_elements', ['objective_element_id'], unique=False)
    op.create_table('nabh_applicability_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('measurable_element_id', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_if_true', sa.String(length=50), nullable=False),
    sa.Column('action_if_false', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['measurable_element_id'], ['nabh_measurable_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_rule_meas_el', 'nabh_applicability_rules', ['measurable_element_id'], unique=False)
    op.create_table('nabh_evidence_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('measurable_element_id', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.Enum('SOP', 'REGISTER', 'TRAINING_RECORD', 'LICENSE', 'AUDIT_LOG', 'PHOTO', 'COMMITTEE_MINUTES', 'TELEMETRY', 'CAPA', name='evidencetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('evidence_frequency', sa.String(length=50), nullable=True),
    sa.Column('minimum_lookback_days', sa.Integer(), nullable=False),
    sa.Column('default_owner_role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['measurable_element_id'], ['nabh_measurable_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_req_meas_el', 'nabh_evidence_requirements', ['measurable_element_id'], unique=False)
    op.create_table('nabh_requirement_citations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('measurable_element_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('page_number', sa.String(length=50), nullable=True),
    sa.Column('clause_text_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['nabh_source_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['measurable_element_id'], ['nabh_measurable_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_citation_document', 'nabh_requirement_citations', ['document_id'], unique=False)
    op.create_index('idx_citation_meas_el', 'nabh_requirement_citations', ['measurable_element_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_citation_meas_el', table_name='nabh_requirement_citations')
    op.drop_index('idx_citation_document', table_name='nabh_requirement_citations')
    op.drop_table('nabh_requirement_citations')
    op.drop_index('idx_evidence_req_meas_el', table_name='nabh_evidence_requirements')
    op.drop_table('nabh_evidence_requirements')
    op.drop_index('idx_app_rule_meas_el', table_name='nabh_applicability_rules')
    op.drop_table('nabh_applicability_rules')
    op.drop_index('idx_meas_element_obj_el', table_name='nabh_measurable_elements')
    op.drop_index('idx_meas_element_edition', table_name='nabh_measurable_elements')
    op.drop_table('nabh_measurable_elements')
    op.drop_index('idx_obj_element_standard', table_name='nabh_objective_elements')
    op.drop_index('idx_obj_element_edition', table_name='nabh_objective_elements')
    op.drop_table('nabh_objective_elements')
    op.drop_index('idx_alert_type', table_name='risk_alerts')
    op.drop_index('idx_alert_severity', table_name='risk_alerts')
    op.drop_index('idx_alert_resolved', table_name='risk_alerts')
    op.drop_table('risk_alerts')
    op.drop_index('idx_standard_edition', table_name='nabh_standards')
    op.drop_index('idx_standard_chapter', table_name='nabh_standards')
    op.drop_table('nabh_standards')
    op.drop_table('nabh_objectives')
    op.drop_index('idx_transaction_date', table_name='fund_transactions')
    op.drop_index('idx_fund_type_date', table_name='fund_transactions')
    op.drop_table('fund_transactions')
    op.drop_index('idx_consent_status', table_name='consent_records')
    op.drop_index('idx_consent_patient', table_name='consent_records')
    op.drop_index('idx_consent_expiry', table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index('idx_compliance_status', table_name='compliance_records')
    op.drop_index('idx_compliance_standard', table_name='compliance_records')
    op.drop_table('compliance_records')
    op.drop_index('idx_bmw_hospital_date', table_name='bmw_logs')
    op.drop_index('idx_bmw_date', table_name='bmw_logs')
    op.drop_index('idx_bmw_category', table_name='bmw_logs')
    op.drop_table('bmw_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('staff')
    op.drop_index('idx_source_doc_edition', table_name='nabh_source_documents')
    op.drop_table('nabh_source_documents')
    op.drop_index('idx_chapter_edition', table_name='nabh_chapters')
    op.drop_table('nabh_chapters')
    op.drop_index('idx_license_status', table_name='licenses')
    op.drop_index('idx_license_expiry', table_name='licenses')
    op.drop_table('licenses')
    op.drop_table('fund_accounts')
    op.drop_table('data_breach_logs')
    op.drop_index('idx_regulatory_source', table_name='regulatory_updates')
    op.drop_index('idx_regulatory_date', table_name='regulatory_updates')
    op.drop_table('regulatory_updates')
    op.drop_table('nabh_editions')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
