"""add_hospital_requirement_state

Revision ID: 8d0e6bace4e6
Revises: 02c7a488c69e
Create Date: 2026-06-08 04:09:13.920186
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8d0e6bace4e6'
down_revision: Union[str, None] = '02c7a488c69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_nabh_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('requirement_id', sa.String(), nullable=False),
    sa.Column('applicability_status', sa.Enum('APPLICABLE', 'CONDITIONAL', 'NOT_APPLICABLE', 'MANUAL_REVIEW', name='applicabilitydefault'), nullable=False),
    sa.Column('applicability_reason', sa.Text(), nullable=True),
    sa.Column('maturity_level', sa.Enum('NON_EXISTENT', 'AD_HOC', 'DEFINED', 'IMPLEMENTED', 'MEASURED', 'OPTIMIZED', name='maturitylevel'), nullable=False),
    sa.Column('evidence_status', sa.Enum('MISSING', 'DRAFT', 'PENDING_VERIFICATION', 'VERIFIED', 'EXPIRED', name='evidencestatus'), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_by', sa.String(), nullable=True),
    sa.Column('readiness_status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'PARTIALLY_COMPLIANT', 'UNDER_REVIEW', 'NOT_APPLICABLE', name='compliancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_reviewed_by'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['nabh_measurable_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'requirement_id', name='uq_hospital_requirement')
    )
    op.create_index('idx_hosp_req_hospital', 'hospital_nabh_requirements', ['hospital_id'], unique=False)
    op.create_index('idx_hosp_req_owner', 'hospital_nabh_requirements', ['owner_id'], unique=False)
    op.create_index('idx_hosp_req_requirement', 'hospital_nabh_requirements', ['requirement_id'], unique=False)
    op.create_index('idx_hosp_req_reviewer', 'hospital_nabh_requirements', ['last_reviewed_by'], unique=False)
    op.create_table('hospital_requirement_evidence_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_requirement_id', sa.String(), nullable=False),
    sa.Column('evidence_requirement_id', sa.String(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_path_or_url', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_requirement_id'], ['nabh_evidence_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_requirement_id'], ['hospital_nabh_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_requirement_id', 'evidence_requirement_id', name='uq_hosp_req_evidence_req')
    )
    op.create_index('idx_evidence_link_evidence_req', 'hospital_requirement_evidence_links', ['evidence_requirement_id'], unique=False)
    op.create_index('idx_evidence_link_requirement', 'hospital_requirement_evidence_links', ['hospital_requirement_id'], unique=False)
    op.create_index('idx_evidence_link_uploader', 'hospital_requirement_evidence_links', ['uploaded_by'], unique=False)
    op.create_index('idx_evidence_link_verifier', 'hospital_requirement_evidence_links', ['verified_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_evidence_link_verifier', table_name='hospital_requirement_evidence_links')
    op.drop_index('idx_evidence_link_uploader', table_name='hospital_requirement_evidence_links')
    op.drop_index('idx_evidence_link_requirement', table_name='hospital_requirement_evidence_links')
    op.drop_index('idx_evidence_link_evidence_req', table_name='hospital_requirement_evidence_links')
    op.drop_table('hospital_requirement_evidence_links')
    op.drop_index('idx_hosp_req_reviewer', table_name='hospital_nabh_requirements')
    op.drop_index('idx_hosp_req_requirement', table_name='hospital_nabh_requirements')
    op.drop_index('idx_hosp_req_owner', table_name='hospital_nabh_requirements')
    op.drop_index('idx_hosp_req_hospital', table_name='hospital_nabh_requirements')
    op.drop_table('hospital_nabh_requirements')
    # ### end Alembic commands ###
