"""add_citation_fields

Revision ID: b6e15beae6ec
Revises: 8d0e6bace4e6
Create Date: 2026-06-08 14:56:45.182734
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'b6e15beae6ec'
down_revision: Union[str, None] = '8d0e6bace4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nabh_requirement_citations', sa.Column('effective_date', sa.DateTime(), nullable=True))
    op.add_column('nabh_requirement_citations', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('nabh_requirement_citations', sa.Column('url', sa.String(length=1000), nullable=True))
    op.add_column('nabh_source_documents', sa.Column('effective_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nabh_source_documents', 'effective_date')
    op.drop_column('nabh_requirement_citations', 'url')
    op.drop_column('nabh_requirement_citations', 'file_path')
    op.drop_column('nabh_requirement_citations', 'effective_date')
    # ### end Alembic commands ###
